# -*- coding: utf-8 -*-
"""Lemmatization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y8BeRiwd7L0ieOY_-pSIkmgKMBoH7gM-
"""

import nltk
nltk.download('punkt_tab')
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk import pos_tag
from nltk.tokenize import word_tokenize
nltk.download('averaged_perceptron_tagger_eng')

lemmatizer = WordNetLemmatizer()

# def get_wordnet_pos(treebank_tag):
#     if treebank_tag.startswith('J'):
#         return wordnet.ADJ
#     elif treebank_tag.startswith('V'):
#         return wordnet.VERB
#     elif treebank_tag.startswith('N'):
#         return wordnet.NOUN
#     elif treebank_tag.startswith('R'):
#         return wordnet.ADV
#     else:
#         return wordnet.NOUN  # Default

sentence = "Cats are running faster than dogs"
words = word_tokenize(sentence)
pos_tags = pos_tag(words)

lemmas = []
for word, tag in pos_tags:
    pos = get_wordnet_pos(tag)
    lemma = lemmatizer.lemmatize(word, pos=pos)
    lemmas.append(lemma)

print(lemmas)
# Output: ['Cat', 'be', 'run', 'fast', 'than', 'dog']

import nltk
nltk.download('averaged_perceptron_tagger_eng')