# -*- coding: utf-8 -*-
"""nlp_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tih6h51XLwIWH8OKiwplEsDzik8kGKu
"""

import nltk
data = "My name is mukul Kanodia!"
tokens = nltk.sent_tokenize(data)
print(tokens)

import nltk
nltk.download('punkt')

data = "My name is mukul Kanodia!"
tokens = nltk.sent_tokenize(data)
print(tokens)

import nltk
nltk.download('punkt_tab')
data = "My name is mukul Kanodia!"
tokens = nltk.sent_tokenize(data)
print(tokens)
# WORDS
tokens=nltk.word_tokenize(data)
print(tokens)