# -*- coding: utf-8 -*-
"""Stemming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESPAHtTQQNweWLhYn0CXBrDX7GVUeYKU
"""

from nltk.stem import PorterStemmer
stemmer=PorterStemmer()
print(stemmer.stem("running"))

from nltk.stem import SnowballStemmer

stemmer = SnowballStemmer("english")

print(stemmer.stem("Playing"))

portstem=PorterStemmer()
words=["play","playing","played","plays"]
for i in words:
  print(i,":",portstem.stem(i))