# -*- coding: utf-8 -*-
"""stopwords.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKnrlS8AnKvTvZbKReIWN5rK1RhhyX8n
"""

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

text="The quick brown fox jumps over the lazy dog."
stop_words=set(stopwords.words('english'))

words=word_tokenize(text)
filtered_text=[word for word in words if word.lower() not in stop_words]
print(filtered_text)