# -*- coding: utf-8 -*-
"""TF-IDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgoLlCfcq5Ywi1dTHoQ1OAJG637OcJNv
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Our two documents
corpus = [
    'The cat sat on the mat.',
    'The dog ate the cat.'
]

# Create the TF-IDF model
tfidf_vectorizer = TfidfVectorizer()

# Generate the TF-IDF score matrix
Y = tfidf_vectorizer.fit_transform(corpus)

# See the vocabulary (the features)
print("Vocabulary: ", tfidf_vectorizer.get_feature_names_out())
# Output: Vocabulary:  ['ate' 'cat' 'dog' 'mat' 'on' 'sat' 'the']

# See the resulting vectors
print("\nTF-IDF Vectors:")
print(Y.toarray())
# Output (values will be different from BoW):
# [[0.         0.47385... 0.         0.6653... 0.6653... 0.6653... 0.3340...]  <-- Doc 1
#  [0.6316...  0.3731...  0.6316...  0.         0.         0.         0.2672...]] <-- Doc 2